version: '3'
services:
  jenkins-server:
    build: .
    environment:
      jenkins_home: "/var/jenkins_home"
      JAVA_OPTS: "-Dhudson.model.UpdateCenter.pluginDownloadReadTimeoutSeconds=240"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 50000:50000
      - 9091:8080
